### ISSUE TITLE
Modeling;Tasks 1; Base line model Form a base line model (Linear Regression Model); Asses the performance metrics , Regularize or hyper parameter tune accordingly 

### ISSUE THREAD

**Issue by N-kioko** [N-kioko/Jumia_Smartphones_Price_Prediction-_Optimizing_Retail_Strategies_through_Data_Analytics#4]

**Comment by N-kioko** [comment]
Tasks 1; Base line model
Form a base line model (Linear Regression Model); Asses the performance metrics , Regularize or hyper parameter tune accordingly
Task 2;
Decision Trees: Useful for capturing non-linear relationships in the data without needing feature scaling. They can handle both numerical and categorical data. 
Task 3;Gradient Boosting Machines (GBM): Another ensemble technique that builds trees sequentially, where each new tree corrects the errors made by the previous ones. It often provides high predictive accuracy.
Task4;
Support Vector Regression (SVR): A powerful regression technique that can handle non-linear relationships using kernel functions.
task5
XGBoost: Advanced gradient boosting algorithms that are efficient and typically yield excellent results in regression tasks.

**Comment by jgatharia** [comment]
This has been done.
